<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2008r2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vmf="http://www.altova.com/MapForce/UDF/vmf" exclude-result-prefixes="vmf xs xsi xsl">
	<xsl:template name="vmf:inputtoresult">
		<xsl:param name="input"/>
		<xsl:choose>
			<xsl:when test="$input='5'">
				<xsl:value-of select="'1-Low'"/>
			</xsl:when>
			<xsl:when test="$input='4'">
				<xsl:value-of select="'2-Medium'"/>
			</xsl:when>
			<xsl:when test="$input='3'">
				<xsl:value-of select="'3-High'"/>
			</xsl:when>
			<xsl:when test="$input='2'">
				<xsl:value-of select="'4-Very High'"/>
			</xsl:when>
			<xsl:when test="$input='1'">
				<xsl:value-of select="'5-Urgent'"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="'5-Urgent'"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/artifact">
		<artifact>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation">
				<xsl:value-of select="'C:/DOCUME~1/jnicolai/workspace/CCF/scripts/exampleschemaHPQC.xsd'"/>
			</xsl:attribute>
			<xsl:for-each select="@artifactMode">
				<xsl:variable name="Vvar190_artifactMode_string" select="string(.)"/>
				<xsl:attribute name="artifactMode">
					<xsl:value-of select="$Vvar190_artifactMode_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@artifactAction">
				<xsl:variable name="Vvar194_artifactAction_string" select="string(.)"/>
				<xsl:attribute name="artifactAction">
					<xsl:value-of select="$Vvar194_artifactAction_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@sourceArtifactVersion">
				<xsl:variable name="Vvar198_sourceArtifactVersion_string" select="string(.)"/>
				<xsl:attribute name="sourceArtifactVersion">
					<xsl:value-of select="$Vvar198_sourceArtifactVersion_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@targetArtifactVersion">
				<xsl:variable name="Vvar202_targetArtifactVersion_string" select="string(.)"/>
				<xsl:attribute name="targetArtifactVersion">
					<xsl:value-of select="$Vvar202_targetArtifactVersion_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@sourceArtifactLastModifiedDate">
				<xsl:variable name="Vvar206_sourceArtifactLastModifiedDate_string" select="string(.)"/>
				<xsl:attribute name="sourceArtifactLastModifiedDate">
					<xsl:value-of select="$Vvar206_sourceArtifactLastModifiedDate_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@targetArtifactLastModifiedDate">
				<xsl:variable name="Vvar210_targetArtifactLastModifiedDate_string" select="string(.)"/>
				<xsl:attribute name="targetArtifactLastModifiedDate">
					<xsl:value-of select="$Vvar210_targetArtifactLastModifiedDate_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@conflictResolutionPriority">
				<xsl:variable name="Vvar214_conflictResolutionPriority_string" select="string(.)"/>
				<xsl:attribute name="conflictResolutionPriority">
					<xsl:value-of select="$Vvar214_conflictResolutionPriority_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@artifactType">
				<xsl:variable name="Vvar218_artifactType_string" select="string(.)"/>
				<xsl:attribute name="artifactType">
					<xsl:value-of select="$Vvar218_artifactType_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@sourceSystemKind">
				<xsl:variable name="Vvar222_sourceSystemKind_string" select="string(.)"/>
				<xsl:attribute name="sourceSystemKind">
					<xsl:value-of select="$Vvar222_sourceSystemKind_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@sourceSystemId">
				<xsl:variable name="Vvar226_sourceSystemId_string" select="string(.)"/>
				<xsl:attribute name="sourceSystemId">
					<xsl:value-of select="$Vvar226_sourceSystemId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@sourceRepositoryKind">
				<xsl:variable name="Vvar230_sourceRepositoryKind_string" select="string(.)"/>
				<xsl:attribute name="sourceRepositoryKind">
					<xsl:value-of select="$Vvar230_sourceRepositoryKind_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@sourceRepositoryId">
				<xsl:variable name="Vvar234_sourceRepositoryId_string" select="string(.)"/>
				<xsl:attribute name="sourceRepositoryId">
					<xsl:value-of select="$Vvar234_sourceRepositoryId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@sourceArtifactId">
				<xsl:variable name="Vvar238_sourceArtifactId_string" select="string(.)"/>
				<xsl:attribute name="sourceArtifactId">
					<xsl:value-of select="$Vvar238_sourceArtifactId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@targetSystemKind">
				<xsl:variable name="Vvar242_targetSystemKind_string" select="string(.)"/>
				<xsl:attribute name="targetSystemKind">
					<xsl:value-of select="$Vvar242_targetSystemKind_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@targetSystemId">
				<xsl:variable name="Vvar246_targetSystemId_string" select="string(.)"/>
				<xsl:attribute name="targetSystemId">
					<xsl:value-of select="$Vvar246_targetSystemId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@targetRepositoryKind">
				<xsl:variable name="Vvar250_targetRepositoryKind_string" select="string(.)"/>
				<xsl:attribute name="targetRepositoryKind">
					<xsl:value-of select="$Vvar250_targetRepositoryKind_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@targetRepositoryId">
				<xsl:variable name="Vvar254_targetRepositoryId_string" select="string(.)"/>
				<xsl:attribute name="targetRepositoryId">
					<xsl:value-of select="$Vvar254_targetRepositoryId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@targetArtifactId">
				<xsl:variable name="Vvar258_targetArtifactId_string" select="string(.)"/>
				<xsl:attribute name="targetArtifactId">
					<xsl:value-of select="$Vvar258_targetArtifactId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depParentSourceRepositoryKind">
				<xsl:variable name="Vvar262_depParentSourceRepositoryKind_string" select="string(.)"/>
				<xsl:attribute name="depParentSourceRepositoryKind">
					<xsl:value-of select="$Vvar262_depParentSourceRepositoryKind_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depParentSourceRepositoryId">
				<xsl:variable name="Vvar266_depParentSourceRepositoryId_string" select="string(.)"/>
				<xsl:attribute name="depParentSourceRepositoryId">
					<xsl:value-of select="$Vvar266_depParentSourceRepositoryId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depParentSourceArtifactId">
				<xsl:variable name="Vvar270_depParentSourceArtifactId_string" select="string(.)"/>
				<xsl:attribute name="depParentSourceArtifactId">
					<xsl:value-of select="$Vvar270_depParentSourceArtifactId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depChildSourceRepositoryKind">
				<xsl:variable name="Vvar274_depChildSourceRepositoryKind_string" select="string(.)"/>
				<xsl:attribute name="depChildSourceRepositoryKind">
					<xsl:value-of select="$Vvar274_depChildSourceRepositoryKind_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depChildSourceRepositoryId">
				<xsl:variable name="Vvar278_depChildSourceRepositoryId_string" select="string(.)"/>
				<xsl:attribute name="depChildSourceRepositoryId">
					<xsl:value-of select="$Vvar278_depChildSourceRepositoryId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depChildSourceArtifactId">
				<xsl:variable name="Vvar282_depChildSourceArtifactId_string" select="string(.)"/>
				<xsl:attribute name="depChildSourceArtifactId">
					<xsl:value-of select="$Vvar282_depChildSourceArtifactId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depParentTargetRepositoryKind">
				<xsl:variable name="Vvar286_depParentTargetRepositoryKind_string" select="string(.)"/>
				<xsl:attribute name="depParentTargetRepositoryKind">
					<xsl:value-of select="$Vvar286_depParentTargetRepositoryKind_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depParentTargetRepositoryId">
				<xsl:variable name="Vvar290_depParentTargetRepositoryId_string" select="string(.)"/>
				<xsl:attribute name="depParentTargetRepositoryId">
					<xsl:value-of select="$Vvar290_depParentTargetRepositoryId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depParentTargetArtifactId">
				<xsl:variable name="Vvar294_depParentTargetArtifactId_string" select="string(.)"/>
				<xsl:attribute name="depParentTargetArtifactId">
					<xsl:value-of select="$Vvar294_depParentTargetArtifactId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depChildTargetRepositoryKind">
				<xsl:variable name="Vvar298_depChildTargetRepositoryKind_string" select="string(.)"/>
				<xsl:attribute name="depChildTargetRepositoryKind">
					<xsl:value-of select="$Vvar298_depChildTargetRepositoryKind_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depChildTargetRepositoryId">
				<xsl:variable name="Vvar302_depChildTargetRepositoryId_string" select="string(.)"/>
				<xsl:attribute name="depChildTargetRepositoryId">
					<xsl:value-of select="$Vvar302_depChildTargetRepositoryId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@depChildTargetArtifactId">
				<xsl:variable name="Vvar306_depChildTargetArtifactId_string" select="string(.)"/>
				<xsl:attribute name="depChildTargetArtifactId">
					<xsl:value-of select="$Vvar306_depChildTargetArtifactId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@errorCode">
				<xsl:variable name="Vvar310_errorCode_string" select="string(.)"/>
				<xsl:attribute name="errorCode">
					<xsl:value-of select="$Vvar310_errorCode_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@transactionId">
				<xsl:variable name="Vvar314_transactionId_string" select="string(.)"/>
				<xsl:attribute name="transactionId">
					<xsl:value-of select="$Vvar314_transactionId_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@includesFieldMetaData">
				<xsl:variable name="Vvar318_includesFieldMetaData_string" select="string(.)"/>
				<xsl:attribute name="includesFieldMetaData">
					<xsl:value-of select="$Vvar318_includesFieldMetaData_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@sourceSystemTimezone">
				<xsl:variable name="Vvar322_sourceSystemTimezone_string" select="string(.)"/>
				<xsl:attribute name="sourceSystemTimezone">
					<xsl:value-of select="$Vvar322_sourceSystemTimezone_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="@targetSystemTimezone">
				<xsl:variable name="Vvar326_targetSystemTimezone_string" select="string(.)"/>
				<xsl:attribute name="targetSystemTimezone">
					<xsl:value-of select="$Vvar326_targetSystemTimezone_string"/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:for-each select="actualHours">
				<xsl:variable name="Vvar330_actualHours_string" select="string(.)"/>
				<BG_ACTUAL_FIX_TIME>
					<xsl:value-of select="$Vvar330_actualHours_string"/>
				</BG_ACTUAL_FIX_TIME>
			</xsl:for-each>
			<xsl:for-each select="QC-Id">
				<xsl:variable name="Vvar334_QC-Id_string" select="string(.)"/>
				<BG_BUG_ID>
					<xsl:value-of select="$Vvar334_QC-Id_string"/>
				</BG_BUG_ID>
			</xsl:for-each>
			<xsl:for-each select="description">
				<xsl:variable name="Vvar338_description_string" select="string(.)"/>
				<BG_DESCRIPTION>
					<xsl:value-of select="$Vvar338_description_string"/>
				</BG_DESCRIPTION>
			</xsl:for-each>
			<xsl:for-each select="CommentText">
				<xsl:variable name="Vvar342_CommentText_string" select="string(.)"/>
				<BG_DEV_COMMENTS>
					<xsl:value-of select="$Vvar342_CommentText_string"/>
				</BG_DEV_COMMENTS>
			</xsl:for-each>
			<xsl:for-each select="estimatedHours">
				<xsl:variable name="Vvar346_estimatedHours_string" select="string(.)"/>
				<BG_ESTIMATED_FIX_TIME>
					<xsl:value-of select="$Vvar346_estimatedHours_string"/>
				</BG_ESTIMATED_FIX_TIME>
			</xsl:for-each>
			<xsl:for-each select="priority">
				<xsl:variable name="Vvar348_priority_string" select="string(.)"/>
				<xsl:variable name="Vvar350_result">
					<xsl:call-template name="vmf:inputtoresult">
						<xsl:with-param name="input" select="$Vvar348_priority_string"/>
					</xsl:call-template>
				</xsl:variable>
				<BG_PRIORITY>
					<xsl:value-of select="$Vvar350_result"/>
				</BG_PRIORITY>
			</xsl:for-each>
			<xsl:for-each select="assignedTo">
				<xsl:variable name="Vvar355_assignedTo_string" select="string(.)"/>
				<BG_RESPONSIBLE>
					<xsl:value-of select="$Vvar355_assignedTo_string"/>
				</BG_RESPONSIBLE>
			</xsl:for-each>
			<xsl:for-each select="status">
				<xsl:variable name="Vvar359_status_string" select="string(.)"/>
				<BG_STATUS>
					<xsl:value-of select="$Vvar359_status_string"/>
				</BG_STATUS>
			</xsl:for-each>
			<xsl:for-each select="title">
				<xsl:variable name="Vvar363_title_string" select="string(.)"/>
				<BG_SUMMARY>
					<xsl:value-of select="$Vvar363_title_string"/>
				</BG_SUMMARY>
			</xsl:for-each>
			<xsl:for-each select="id">
				<xsl:variable name="Vvar367_id_string" select="string(.)"/>
				<BG_USER_01>
					<xsl:value-of select="$Vvar367_id_string"/>
				</BG_USER_01>
			</xsl:for-each>
		</artifact>
	</xsl:template>
</xsl:stylesheet>
